{% set version = "0.0.9" %}

package:
  name: mmgp
  version: {{ version }}

source:
  url: https://gitlab.com/drti/mmgp/-/archive/{{ version }}/mmgp-{{ version }}.tar.gz
  sha256: 7a78543ae7ad084c20c093f2c5d90af2f53513bb4d1f7f9e364be5df8245e284

build:
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools
    - setuptools-scm
    - pip

  run:
    - python >=3.11
    - plaid =0.1.6
    - muscat =2.4.1
    - scikit-learn
    - gpy
    
test:
  requires:
    - pytest
    - deepdiff
  imports:
    - mmgp
  source_files:
    - tests
    - examples
  commands:
    - cd tests
    - python -m pytest
    - cd ../examples
    - python run_examples.py --backend scikit-learn
    - python run_examples.py --backend GPy

about:
  home: https://gitlab.com/drti/mmgp
  summary: 'Mesh Morphing Gaussian Process (MMGP)'
  description: |
    MMGP is the name of the numerical method proposed at SafranTech, the research center of Safran group, in the paper: Mesh Morphing Gaussian Process-based machine learning method for regression of physical problems under non-parameterized geometrical variability. MMGP also refers to this library, which implements this methods.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://mmgp.readthedocs.io
  dev_url: https://gitlab.com/drti/mmgp

extra:
  recipe-maintainers:
    - bstaber
    - casenave
    - xroynard
